#!/bin/bash

touch "${HOME}/.npmrc"

docker run \
    -it --rm \
    --init \
    -a stdin -a stdout -a stderr \
    -v "${HOME}/.npmrc:/root/.npmrc" \
    -v "$( pwd )":/data \
    -w /data \
    magmanite/npm-cli \
    "$@"
