#!/bin/bash

touch "${HOME}/.npmrc"

docker run \
    -i --rm \
    --init \
    -a STDIN -a STDOUT -a STDERR \
    --user "$( id -u ):$( id -g )" \
    -v "${HOME}/.npmrc:/.npmrc" \
    -v "$( pwd )":/data \
    -w /data \
    magmanite/npm-cli \
    "$@"
