#!/bin/bash
docker run \
    -i --rm \
    --init \
    --user "$( id -u ):$( id -g )" \
    -a STDIN -a STDOUT -a STDERR \
    -v "$( pwd )":/data \
    -w /data \
    magmanite/angular-cli \
    "$@"
