#!/bin/bash
# This is a convinence script to run Cargo from your CLI.
# It utilises a common caching volume so that it doesn't have to keep downloading dependencies.

CARGO_CACHE_VOLUME="rust-cargo-registry-cache"

docker run -it --rm --init \
    -v "$( pwd )":/work \
    -v "${CARGO_CACHE_VOLUME}":/usr/local/cargo/registry \
    -w /work \
    --user "$( id -u):$( id -g )" \
    magmanite/rust-build-alpine \
    cargo "$@"
